---
- name: install zsh packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  tags: [packages]
  with_items:
    - zsh
    - zsh-doc
    - curl

- name: Clone oh-my-zsh repo
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git
       dest={{ home_dir }}/.oh-my-zsh accept_hostkey=yes

- name: Create a new zsh config from the template in the repo
  command: cp {{ home_dir }}/.oh-my-zsh/templates/zshrc.zsh-template {{ home_dir }}/.zshrc

