---
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: Update all packages
      apt: upgrade=dist
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - libxslt1-dev
        - libxml2-dev
        - git
        - python2.7
        - python-pip
        - python-psycopg2
        - python-yaml
        - python-paramiko
        - python-jinja2
        - python-dev
        - subversion
        - winbind
        - build-essential
        - checkinstall
        - check
        - zip
        - unzip
        - libaio1
        - openssh-server
        - g++
        - libssl-dev
        - dos2unix
        - alien
        - htop
        - libpq-dev
        - git-svn
        - gawk
        - apt-transport-https
        - mercurial
        - rlwrap
        - libcurl4-openssl-dev
        - cloc
        - cowsay
        - pwgen

    - name: Ensure that ansible_cache_dir directory exists
      file: path={{ ansible_cache_dir }} state=directory
      sudo: yes
